version: '3'
services:
  elixir:
    build: .
    volumes:
      - .:/home/app
    ports:
      - 4000:4000
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./docker/postgres/.env
    ports:
      - 5432:5432
